namespace raycaster
{
    public enum AnimationCue
    {
    }
    public enum SoundCue
    {
        MenuMusic,
        IntroMusic,
        GamePlayMusic01,
        GamePlayMusic02,
        GamePlayMusic03,
        Gunshot01,
        Gunshot03,
        Gunshot02,
        Pistol1,
        Pistol2,
        Ricochet1,
        Ricochet2,
        Ricochet3,
        MonsterKill,
        UltraKill,
        MultiKill,
        TripleKill,
        DoubleKill,
        PlayerPain2,
        PlayerPain1,
        PlayerDies,
        EnemyPain,
        GatlingGun,
        Knife,
        MachineGun,
        Rifle2,
        Rifle1,
        AlarmSound,
        MeinLeben,
        OpenDoor,
        CloseDoor,
        Achtung,
        Alarm,
        WerDa
    }
}